### ISSUE TITLE
How to get open(private in ColorPicker class) value?

### ISSUE THREAD

**Issue by bitnick10** [XeniaPhe/In-Game-Color-Picker-For-Unity#1]

**Comment by XeniaPhe** [comment]
I'm sorry for the late reply, honestly I wasn't expecting an issue for the repo. Looking at the code now, I realize I should've made a getter for it. One could use reflection to get the value or just tracked the opening and closing events to determine whether it is open or not, though these are just workarounds. I'll write the getter now but I hope you fixed your problem on your end!

**Comment by XeniaPhe** [comment]
Getter written
